spring:
  profiles:
    active:
      - usage_message
  application:
    name: usage_message

  rabbitmq:
    host: 192.168.23.111
    port: 5672
    username: user
    password: password

tutorial:
  client:
    duration: 100000 # 运行10s